alias: Prep Room Before Scheduled Meeting
trigger:
  - platform: calendar
    event: start
    entity_id: calendar.karthik_calendar
condition:
  - condition: template
    value_template: "{{ state_attr('calendar.karthik_calendar', 'message') | lower | regex_search('meeting') }}"
action:
  - service: switch.turn_on
    target:
      entity_id: switch.office_fan
  - service: light.turn_on
    data:
      entity_id: light.desk_lamp
      brightness_pct: 100
